pydjangoenv/PaPlaya/PaPlaya/urls.py
from django.contrib import admin
from django.urls import include, path
#from django.http import HttpResponse

#def index(request):
    #return HttpResponse('<p>Hello! Weclome to <b>PaPlaya</b>!</p>')

#def fgrub(request):
    #return HttpResponse('<p>Our featured drink for today is <b>Papaya Shots</b>!</p>')

urlpatterns = [
    #path('', index),
    #path('featuredgrub/', fgrub),
    path('webkiosk/', include('webkiosk.urls')),
    path('admin/', admin.site.urls),
]
#user can visit a url - 127.0.0.1:8000/featuredPap

pydjangoenv/PaPlaya/webkiosk/urls.py
from django.urls import path
from . import views

app_name = 'webkiosk'
urlpatterns = [
    path('', views.index, name='index'),
    path('menu/', views.listfood, name='food-list'),
    path('food/new/', views.createfood, name='food-create'),
    path('food/<int:pk>', views.detailfood, name='food-detail'),
    path('food/<int:pk>/edit/', views.updatefood, name='food-update'),
    path('food/<int:pk>/delete/', views.deletefood, name='food-delete'),
]

#webkiosk/food/4

pydjangoenv/PaPlaya/webkiosk/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.id}: {self.firstname} {self.lastname}, {self.address}, {self.city}'

class Food(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f'{self.id}: {self.name}, {self.description}, {self.price}'

class Order(models.Model):
    PAYMENT_MODE_CHOICES = [
        ('CH', 'Cash'),
        ('CD', 'Card')
    ]
    orderdatetime = models.DateTimeField(auto_now_add=True)
    paymentmode = models.CharField(max_length=2, choices=PAYMENT_MODE_CHOICES) #CH, CD
    quantity = models.IntegerField()

    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id}: {self.customer.firstname} {self.customer.lastname}, {self.food.name}, {self.quantity}, {self.paymentmode}, {self.orderdatetime}'

pydjangoenv/PaPlaya/webkiosk/forms.py
from django.forms import ModelForm
from .models import Customer, Food, Order

class FoodForm(ModelForm):
    class Meta:
        model = Food
        fields = ['name', 'description','price']

pydjangoenv/PaPlaya/webkiosk/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
# Create your views here.

from .models import Customer, Food, Order
from .forms import FoodForm

def index(request):
    #return HttpResponse('<p>Welcom to the PaPlaya Web Kiosk</p>')
    return render(request, 'webkiosk/welcome.html')


def listfood(request):
    context = {
        'foodlist': Food.objects.all(),
        'testitem': 'chair'
    }
    return render(request, 'webkiosk/food.html', context)

def createfood(request):
    if request.method == 'GET':
        form = FoodForm()
    elif request.method == 'POST':
        form = FoodForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('webkiosk:food-list')


    context = {'form': form}
    return render(request, 'webkiosk/food_form.html', context)

def detailfood(request, pk):
    food = Food.objects.get(id=pk)
    context = {'food':food}
    return render(request, 'webkiosk/food_detail.html', context)

def updatefood(request, pk):
    food = Food.objects.get(id=pk)
    if request.method == 'GET':
        form = FoodForm (instance=food)

    elif request.method == 'POST':
        form = FoodForm(request.POST, instance=food)
        if form.is_valid():
            form.save()
            messages.success(request, 'Food record successfully updated.')
    context = {'form':form}
    return render(request, 'webkiosk/food_form.html', context)

def deletefood(request, pk):
    food = Food.objects.get(id=pk)
    if request.method == 'GET':
        context = {'food':food}
        return render(request, 'webkiosk/food_delete.html', context)
    elif request.method == 'POST':
            food.delete()
            return redirect('webkiosk:food-list')

pydjangoenv/PaPlaya/webkiosk/templates/webkiosk/base.html
{% load static %}


<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block pagetitle %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'webkiosk/styles/main.css' %}">
  </head>
  <body>
    <header>
      <h1>PaPlaya</h1>
      <p>Get your food now!</p>
      <img src="{% static 'webkiosk/images/sun.jpg' %}">
    </header>

    {% block mainnav %}
    <nav>
      <ul>
        <li><a href="{% url 'webkiosk:food-list' %}">Food Menu</a></li>
        <li><a href="{% url 'webkiosk:food-create' %}">Add Food</a></li>
      </ul>
    </nav>
    {% endblock %}


    <main>
      {% block maincontent %}

      {% endblock %}
    </main>
  </body>
</html>

pydjangoenv/PaPlaya/webkiosk/templates/webkiosk/food.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}PaPlaya - Food List{% endblock %}

{% block maincontent %}
<h2>Menu</h2>
<ol>
  {% for food in foodlist %}
  <li>{{ food.name }} | Php {{ food.price}} |
     <a href="{% url 'webkiosk:food-detail' food.id %}">More Info</a> |
      <a href="{% url 'webkiosk:food-update' food.id %}">Edit</a> |
      <a href="{% url 'webkiosk:food-delete' food.id %}">Delete</a> |

  </li>
  {% endfor %}
</ol>
<p>The value of testitem is {{ testitem }}.</p>
{% endblock %}

pydjangoenv/PaPlaya/webkiosk/templates/webkiosk/food_delete.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}PaPlaya - Delete {{ food.name }} {% endblock %}

{% block mainnav %} {% endblock %}

{% block maincontent %}
<h2>Delete Food</h2>
<form method='post'>
  {% csrf_token %}
  <p>Are you sure you want to delete <b>{{ food.name }}</b></p>
  <a href="{% url 'webkiosk:food-list' %}">Cancel</a>
  <input type="submit" value="Yes">
</form>
{% endblock %}

pydjangoenv/PaPlaya/webkiosk/templates/webkiosk/food_detail.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}PaPlaya - {{ food.name }}{% endblock %}

{% block maincontent %}
<h2>{{ food.name }}</h2>
<ul>
  <li>Description: {{ food.description }}</li>
  <li>Price: Php {{ food.price }}</li>
</ul>
{% endblock %}

pydjangoenv/PaPlaya/webkiosk/templates/webkiosk/food_form.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}PaPlaya - Add or Edit Food{% endblock %}

{% block maincontent %}
<h2>Add or Edit Food</h2>

<form method="post">
  {% csrf_token %}
  {{ form.as_ul }}
  <input type="submit" name="" value="Submit">
</form>

<ul>
  {% for message in messages %}
  <li>{{ message }}</li>
  {% endfor %}
</ul>


{% endblock %}

pydjangoenv/PaPlaya/webkiosk/templates/webkiosk/welcome.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}PaPlaya Web Kiosk :)) {% endblock %}

{% block maincontent %}
<h2>Welcome!</h2>
<p>Welcome to the PaPlaya Web Kiosk! Have a nice day :)</p>
{% endblock %}